[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "resnet-comparison-project"
version = "0.1.0"
dependencies = [
    "torch",
    "numpy",
    "pandas",
    "matplotlib"
]